// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRitpLb692LgtNoZD0j0rYR9j-fYibaI',
    appId: '1:158380731477:web:6cc69bb0352301503d78dc',
    messagingSenderId: '158380731477',
    projectId: 'warehouse-18f04',
    authDomain: 'warehouse-18f04.firebaseapp.com',
    storageBucket: 'warehouse-18f04.appspot.com',
    measurementId: 'G-S7RNK0SPYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2v3N2LLxcEI5fW9HYH11UY1xDDeEmjD4',
    appId: '1:158380731477:android:3d4e71b4b85defb33d78dc',
    messagingSenderId: '158380731477',
    projectId: 'warehouse-18f04',
    storageBucket: 'warehouse-18f04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-7jQRj4GRLFNJno0lhRwNcwSZxds6t8Q',
    appId: '1:158380731477:ios:fd6cfba2649bdbc13d78dc',
    messagingSenderId: '158380731477',
    projectId: 'warehouse-18f04',
    storageBucket: 'warehouse-18f04.appspot.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-7jQRj4GRLFNJno0lhRwNcwSZxds6t8Q',
    appId: '1:158380731477:ios:03c0fbd6d4d1f5943d78dc',
    messagingSenderId: '158380731477',
    projectId: 'warehouse-18f04',
    storageBucket: 'warehouse-18f04.appspot.com',
    iosBundleId: 'com.int2.flutterEcommerceTemplate',
  );
}
